# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c13f3a0dad4396e9ecdb6f0dcdd9e18074ced7a8d2fcf42b1d492bbdff1ce2024d498027023533982118c33b3976c5a0337c4bfd4bf9105101e89f1827d7d552

test:
  secret_key_base: bb094ce3c135198cbbd17146d1dd58c6f23fabe8ce43d0c134d829199b89f03bf9fc94388539a607c726505be3202dd79e97e11fc2251f7c52a6dbb04792c0f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
